apiVersion: polaris.ricochet/v1alpha1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/name: polaris
    app.kubernetes.io/managed-by: kustomize
  name: gateway-sample
spec:
  # TODO(user): Add fields here
