name: CI

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  chores:
    name: chores
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: generate and format code
        run: |
          make
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: generate and format code"
          # Ignore file changes in the root directory.
          file_pattern: '**/**'

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: run all tests
        run: |
          make test
